/*TMODJS:{"debug":true,"version":109,"md5":"6d7f563c1121b5462a367cd9804e5a68"}*/
define(function(require) {
    return require("/js/template/template")("arrange/arrangeCenter/transferView/addbusTransfer", function($data, $filename) {
        try {
            var $utils = this, $line = ($utils.$helpers, 0), $escape = $utils.$escape, shuttleType = $data.shuttleType, $out = "";
            return $out += '<div class=" mar-t-20 mar-l-10" id="transfer-bus-arrange-frame" data-target="bus"> <form class="T-search-area " role="form" onsubmit="return false"> <div class="form-inline"> <div class="form-group mar-r-10"> <label>收客单号</label> <input type="text" class="form-control" name="tgOrderNumber" placeholder="收客单号" /> </div> <div class="form-group mar-r-10"> <label>中转单号</label> <input type="text" class="form-control" name="orderNumber" placeholder="中转单号" /> </div> <div class="form-group mar-r-20"> <label>客人</label> <input type="text" class="form-control" value="" name="touristName" placeholder="客人" /> </div> <div class="form-group "> <label>线路产品 </label> <input class="form-control" name="lineProductName" value="" placeholder="线路产品" type="text" /> </div> <div class="form-group mar-r-10 mar-l-5"> <label>班次 </label> <input class="form-control" name="shift" value="" placeholder="班次" type="text" /> </div> <div class="form-group mar-l-10"> <label class="pos-rel"> <input type="checkbox" class="ace T-assign-check"> <span class="lbl"></span> </label> <label>指派给我</label> </div> <div class="form-group "> <button class=" btn-sm mar-r-10 search-btn T-search"> <i class="ace-icon fa fa-search"></i> 搜索 </button> </div> <input type="hidden" name="shuttleType" value="', 
            $line = 36, $out += $escape(shuttleType), $out += '"> </div> <div class="form-inline hct-search-area"> </div> </form> <div class="T-table-area"> </div> <button class="btn btn-block btn-primary T-confirm"> <i class="ace-icon fa fa-check"></i> 提交信息 </button> </div> ', 
            new String($out);
        } catch (e) {
            throw {
                filename: $filename,
                name: "Render Error",
                message: e.message,
                line: $line,
                source: '<div class=" mar-t-20 mar-l-10" id="transfer-bus-arrange-frame" data-target="bus">\r\n    <form class="T-search-area " role="form" onsubmit="return false">\r\n        <div class="form-inline">\r\n            <div class="form-group mar-r-10">\r\n                <label>收客单号</label>\r\n                <input type="text" class="form-control" name="tgOrderNumber" placeholder="收客单号" />\r\n            </div>\r\n            <div class="form-group mar-r-10">\r\n                <label>中转单号</label>\r\n                <input type="text" class="form-control" name="orderNumber" placeholder="中转单号" />\r\n            </div>\r\n            <div class="form-group mar-r-20">\r\n                <label>客人</label>\r\n                <input type="text" class="form-control" value="" name="touristName" placeholder="客人" />\r\n            </div>\r\n            <div class="form-group ">\r\n                <label>线路产品 </label>\r\n                <input class="form-control" name="lineProductName" value="" placeholder="线路产品" type="text" />\r\n            </div>\r\n            <div class="form-group mar-r-10 mar-l-5">\r\n                <label>班次 </label>\r\n                <input class="form-control" name="shift" value="" placeholder="班次" type="text" />\r\n            </div>\r\n            <div class="form-group  mar-l-10">\r\n                <label class="pos-rel">\r\n                    <input type="checkbox" class="ace T-assign-check">\r\n                     <span class="lbl"></span>\r\n                </label>\r\n                <label>指派给我</label>\r\n            </div>\r\n            <div class="form-group ">\r\n                <button class=" btn-sm mar-r-10 search-btn T-search">\r\n                    <i class="ace-icon fa fa-search"></i> 搜索\r\n                </button>\r\n            </div>\r\n            <input type="hidden" name="shuttleType" value="{{shuttleType}}">\r\n        </div>\r\n        <div class="form-inline hct-search-area">\r\n        </div>\r\n    </form>\r\n    <div class="T-table-area">\r\n    </div>\r\n    <button class="btn btn-block btn-primary T-confirm"> <i class="ace-icon fa fa-check"></i> 提交信息 </button>\r\n</div>\r\n'.split(/\n/)[$line - 1].replace(/^\s+/, "")
            };
        }
    });
});