/*TMODJS:{"debug":true,"version":21,"md5":"2a1ed467fec59e10a07e9f2c81664e53"}*/
define(function(require) {
    return require("../../../template")("resource/touristGroupN/view/guestInfo", function($data, $filename) {
        try {
            var $utils = this, $helpers = $utils.$helpers, $line = 0, $string = $utils.$string, $out = "";
            return $out += '<div class="container-fluid mar-t-20"> <div class="row"> <div class="col-xs-12 mar-t-20"> <div class="pull-left"> <span class="necessary">*</span>人数：大人 <span class="necessary">*</span> <input type="text" class="w-50"> 小孩 <input type="text" class="w-50"> </div> <div class="pull-right"> <button class="btn btn-sm btn-success T-add-tourist"> <i class="ace-icon fa fa-plus"></i> 添加成员 </button> <button class="btn btn-sm btn-success T-add-tourist-more"> <i class="ace-icon fa fa-plus"></i> 批量添加 </button> </div> </div> <div class="col-xs-12 mar-t-10"> <table class="table table-striped table-new table-bordered table-hover"> <thead> <tr> <th>序号</th> <th>姓名</th> <th>手机号码</th> <th>证件类型</th> <th>证件号</th> <th>设为联系人</th> <th>操作</th> </tr> </thead> <tbody class="T-addTouristTbody"> <tr> <td>1</td> <td><input type="text" class="col-xs-12"></td> <td><input type="text" class="col-xs-12"></td> <td> <select class="col-xs-12" name="idCardType"> ', 
            $line = 33, $out += $string($helpers.getCardOption("1")), $out += ' </select> </td> <td><input type="text" class="col-xs-12"></td> <td> <label class="control-label"> <input type="checkbox" name="isContactUser" class="ace"> <span class="lbl"></span> </label> </td> <td><a class="cursor">删除</a></td> </tr> </tbody> </table> </div> <div class="col-xs-12 mar-t-20 mar-b-10 text-center"> <button class="btn btn-sm btn-primary otherButton" style="height: auto;"> <i class="ace-icon fa fa-check"></i> 保存 </button> </div> </div> </div>', 
            new String($out);
        } catch (e) {
            throw {
                filename: $filename,
                name: "Render Error",
                message: e.message,
                line: $line,
                source: '<div class="container-fluid mar-t-20">\r\n	<div class="row">\r\n		<div class="col-xs-12 mar-t-20">\r\n			<div class="pull-left">\r\n				<span class="necessary">*</span>人数：大人 <span class="necessary">*</span> <input type="text" class="w-50">\r\n				小孩 <input type="text" class="w-50">\r\n			</div>\r\n			<div class="pull-right">\r\n				<button class="btn btn-sm btn-success T-add-tourist"> <i class="ace-icon fa fa-plus"></i> 添加成员 </button>\r\n				<button class="btn btn-sm btn-success T-add-tourist-more"> <i class="ace-icon fa fa-plus"></i> 批量添加 </button>\r\n			</div>\r\n		</div>\r\n		<div class="col-xs-12 mar-t-10">\r\n			<table class="table table-striped table-new table-bordered table-hover">\r\n				<thead>\r\n					<tr>\r\n						<th>序号</th>\r\n						<th>姓名</th>\r\n						<th>手机号码</th>\r\n						<th>证件类型</th>\r\n						<th>证件号</th>\r\n						<th>设为联系人</th>\r\n						<th>操作</th>\r\n					</tr>\r\n				</thead>\r\n				<tbody class="T-addTouristTbody">\r\n					<tr>\r\n						<td>1</td>\r\n						<td><input type="text" class="col-xs-12"></td>\r\n						<td><input type="text" class="col-xs-12"></td>\r\n						<td>\r\n							<select class="col-xs-12" name="idCardType">\r\n								{{#"1" | getCardOption}}\r\n							</select>\r\n						</td>\r\n						<td><input type="text" class="col-xs-12"></td>\r\n						<td>\r\n							<label class="control-label">\r\n								<input type="checkbox" name="isContactUser" class="ace">\r\n								<span class="lbl"></span>\r\n							</label>\r\n						</td>\r\n						<td><a class="cursor">删除</a></td>\r\n					</tr>\r\n				</tbody>\r\n			</table>\r\n		</div>\r\n		<div class="col-xs-12 mar-t-20 mar-b-10 text-center">\r\n			<button class="btn btn-sm btn-primary otherButton" style="height: auto;"> <i class="ace-icon fa fa-check"></i> 保存 </button>\r\n		</div>\r\n	</div>\r\n</div>'.split(/\n/)[$line - 1].replace(/^\s+/, "")
            };
        }
    });
});